on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy the docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the local version of the plugin
        run: npm run build

      # Symlinks do not work in GitHub CI, so we need to use the `--install-links` option.
      - name: Install the local version of the plugin
        run: npm link && npm link --install-links typedoc-plugin-extras

      - name: Build the docs
        run: npx typedoc --plugin typedoc-plugin-extras --favicon public/favicon.ico --footerLastModified --footerTypedocVersion src/main.ts --out docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
